/**
 * Long-form evergreen guides — US tariffs, HTS codes, customs, and import strategy.
 * Hub pages that link deep into the country × product × HTS code matrix.
 * Each guide targets a high-intent importer question with current 2025-2026 numbers.
 */

export interface Guide {
  slug: string;
  title: string;
  description: string;
  intro: string; // HTML
  sections: Array<{ heading: string; html: string }>;
  faqs: Array<{ question: string; answer: string }>;
  category: string;
  updatedAt: string;
}

const u = '2026-04-10';

export const guides: Guide[] = [
  {
    slug: 'hts-codes-explained',
    title: 'HTS Codes Explained: How to Find Your Product\'s Tariff Rate',
    description: 'The 10-digit Harmonized Tariff Schedule structure, how to navigate the 99 chapters, how to request a CBP binding ruling, and the free USITC lookup tools every importer needs.',
    category: 'HTS & Classification',
    updatedAt: u,
    intro: `<p>Every product imported into the United States must be classified under a 10-digit Harmonized Tariff Schedule (HTS) code. The code determines the tariff rate, the applicable trade remedies, the eligible free trade agreements, and the customs documentation required. Misclassifying a product can result in back duties, penalties, and in severe cases, seizure. Yet most new importers have no idea how to find the right HTS code for their products. This guide explains the HTS structure, how to search it, how to interpret the results, and what to do when the answer isn't obvious.</p>`,
    sections: [
      {
        heading: 'The 10-digit HTS structure',
        html: `<p>The US Harmonized Tariff Schedule is maintained by the US International Trade Commission (USITC) and used by US Customs and Border Protection (CBP) to classify imported goods. The 10-digit code breaks down like this:</p><ul><li><strong>Digits 1-2 (Chapter):</strong> one of 99 broad product categories (e.g., 01 = live animals, 61 = apparel, 85 = electrical machinery)</li><li><strong>Digits 3-4 (Heading):</strong> more specific grouping within the chapter (e.g., 6104 = women's suits and dresses)</li><li><strong>Digits 5-6 (Subheading):</strong> international 6-digit code used by all WTO members (6104.42 = women's dresses of cotton)</li><li><strong>Digits 7-8 (US-specific subheading):</strong> additional US-specific breakdown</li><li><strong>Digits 9-10 (Statistical suffix):</strong> further detail for trade statistics</li></ul><p>The first 6 digits are standardized globally under the WCO Harmonized System — an HTS code that starts with 6104.42 means "women's dresses of cotton" in any country. Digits 7-10 are US-specific and vary by country.</p><p>Example: HTS code 6104.42.00.10 = "Women's dresses, knitted or crocheted, of cotton, containing 36% or more by weight of wool or fine animal hair" — a very specific classification with its own tariff rate.</p>`,
      },
      {
        heading: 'The 99 chapters: a navigation map',
        html: `<p>HTS Chapters are grouped into 21 broad sections. Knowing which section and chapter your product belongs to is the first step in finding the right code:</p><ul><li><strong>Section I (Chapters 1-5):</strong> Live animals and animal products</li><li><strong>Section II (Chapters 6-14):</strong> Vegetable products</li><li><strong>Section III (Chapter 15):</strong> Animal and vegetable fats and oils</li><li><strong>Section IV (Chapters 16-24):</strong> Prepared foodstuffs, beverages, tobacco</li><li><strong>Section V (Chapters 25-27):</strong> Minerals, fuels, and ores</li><li><strong>Section VI (Chapters 28-38):</strong> Chemicals</li><li><strong>Section VII (Chapters 39-40):</strong> Plastics and rubber</li><li><strong>Section VIII (Chapters 41-43):</strong> Leather, furs, skins</li><li><strong>Section IX (Chapters 44-46):</strong> Wood, cork, straw</li><li><strong>Section X (Chapters 47-49):</strong> Pulp, paper, printed products</li><li><strong>Section XI (Chapters 50-63):</strong> Textiles and apparel</li><li><strong>Section XII (Chapters 64-67):</strong> Footwear, headgear, umbrellas</li><li><strong>Section XIII (Chapters 68-70):</strong> Stone, plaster, cement, glass</li><li><strong>Section XIV (Chapter 71):</strong> Pearls, precious stones, metals</li><li><strong>Section XV (Chapters 72-83):</strong> Base metals</li><li><strong>Section XVI (Chapters 84-85):</strong> Machinery and electrical equipment</li><li><strong>Section XVII (Chapters 86-89):</strong> Vehicles, aircraft, vessels</li><li><strong>Section XVIII (Chapters 90-92):</strong> Optical, photographic, musical instruments</li><li><strong>Section XIX (Chapter 93):</strong> Arms and ammunition</li><li><strong>Section XX (Chapters 94-96):</strong> Miscellaneous manufactured articles</li><li><strong>Section XXI (Chapters 97-99):</strong> Works of art, antiques, special classifications</li></ul><p>Chapters 98 and 99 are special — Chapter 98 is for specific US classifications (returned goods, personal effects), Chapter 99 is for temporary modifications including most trade remedy tariffs like Section 301 China tariffs.</p>`,
      },
      {
        heading: 'How to search for your product\'s HTS code',
        html: `<p>Four free tools for HTS lookup:</p><ol><li><strong>USITC HTS Search (hts.usitc.gov):</strong> the official US government source. Full text search, browseable chapter structure, and each code links to the complete description, general rate, special rates, and Chapter 99 modifications.</li><li><strong>CBP CROSS (cross.cbp.gov):</strong> Customs Rulings Online Search System. Contains thousands of binding tariff classification rulings for specific products. If a similar product has been ruled on, the decision applies to yours.</li><li><strong>USITC DataWeb (dataweb.usitc.gov):</strong> historical trade data by HTS code, showing import volumes, values, and duty rates by country.</li><li><strong>Schedule B Search (uscensus.gov):</strong> for exports. Schedule B codes are similar to HTS but used for outbound shipments.</li></ol><p>Search strategy:</p><ul><li><strong>Start with the general product type,</strong> not brand or trade name. "Wireless headphones" not "AirPods."</li><li><strong>Identify the primary material or function.</strong> A leather watch strap might classify under leather (Chapter 42) or watches (Chapter 91) depending on whether it's sold separately or with a watch.</li><li><strong>Read the chapter and heading notes</strong> — they contain critical exclusions. Many products that "seem like" a category are excluded by notes and classified elsewhere.</li><li><strong>Check CBP CROSS for similar products.</strong> Rulings are binding and searchable — if CBP has ruled on a similar product, that ruling applies.</li></ul>`,
      },
      {
        heading: 'The General Rules of Interpretation (GRI)',
        html: `<p>When multiple HTS codes seem to apply, the WCO's General Rules of Interpretation (GRI) tell you which one wins. The GRI are applied in order:</p><ol><li><strong>GRI 1:</strong> Classification is determined by the terms of the headings and relative section or chapter notes. Read the headings and notes first.</li><li><strong>GRI 2a:</strong> Incomplete or unfinished articles are classified as if complete, as long as they have the essential character.</li><li><strong>GRI 2b:</strong> Mixtures and composite goods classified by their essential character.</li><li><strong>GRI 3:</strong> When 2+ headings could apply:<ul><li><strong>3a:</strong> more specific description wins over general</li><li><strong>3b:</strong> composite goods classified by component giving essential character</li><li><strong>3c:</strong> if still tied, last in numerical order wins</li></ul></li><li><strong>GRI 4:</strong> Goods not classifiable under 1-3 go in the heading for "kindred" goods.</li><li><strong>GRI 5:</strong> Containers specifically designed for the article are classified with the article.</li><li><strong>GRI 6:</strong> Subheading classification follows the same rules as heading classification.</li></ol><p>GRI 3a is the most commonly invoked rule. Example: a set containing a leather wallet and a metal money clip. Each item has its own heading, but the combination has none. Under GRI 3a, you look for the most specific description — if the wallet is the dominant item, it classifies under leather goods (4202).</p>`,
      },
      {
        heading: 'Getting a binding ruling from CBP',
        html: `<p>If you're unsure about the correct classification and want legal certainty, you can request a <strong>binding ruling</strong> from US Customs and Border Protection. The process:</p><ol><li><strong>Submit a ruling request</strong> through CBP's eRuling Template system. Include product description, photos, materials, intended use, country of origin, and expected HTS code.</li><li><strong>CBP reviews and issues a ruling letter</strong> within 30-90 days. The letter is legally binding for any importation by the requester.</li><li><strong>Costs:</strong> free. No filing fee.</li><li><strong>Publication:</strong> rulings are published on CBP CROSS and available to anyone. They set precedent for similar products.</li></ol><p>When to request a ruling:</p><ul><li>Product has significant tariff rate difference between possible classifications</li><li>Product is novel and not covered by existing rulings</li><li>You're planning high-volume imports and want certainty</li><li>You disagree with a customs broker's proposed classification</li></ul><p>A binding ruling protects you from CBP reclassification penalties later. Without one, CBP can reclassify your goods at any time and assess back duties plus penalties.</p>`,
      },
      {
        heading: 'Penalties for misclassification',
        html: `<p>CBP can and does audit imports for correct classification. Penalties for misclassification:</p><ul><li><strong>Back duties:</strong> the difference between what you paid and what you should have paid, over the past 5 years (or longer for fraud cases)</li><li><strong>Negligence penalty:</strong> up to 2x the duty underpayment</li><li><strong>Gross negligence penalty:</strong> up to 4x the duty underpayment</li><li><strong>Fraud penalty:</strong> up to the full value of the merchandise (not just the duty)</li><li><strong>Seizure:</strong> in extreme cases</li></ul><p>CBP typically starts with the negligence standard. To escape penalty, the importer must show "reasonable care" — which generally means consulting a licensed customs broker, requesting binding rulings for uncertain cases, and maintaining documentation.</p><p>"I didn't know" is not a defense. The importer of record is legally responsible for correct classification regardless of whether they handled the import themselves or used a broker.</p>`,
      },
    ],
    faqs: [
      { question: 'What is an HTS code?', answer: 'A 10-digit Harmonized Tariff Schedule code that classifies imported goods for tariff and statistical purposes. The first 6 digits are internationally standardized under the WCO Harmonized System; digits 7-10 are US-specific. Every product imported into the US must be classified under an HTS code.' },
      { question: 'How do I find the HTS code for my product?', answer: 'Use the USITC HTS Search at hts.usitc.gov, CBP CROSS ruling database at cross.cbp.gov, and the chapter notes to narrow down the correct classification. For complex or novel products, request a binding ruling from CBP (free, 30-90 day turnaround).' },
      { question: 'What happens if I use the wrong HTS code?', answer: 'CBP can audit and reclassify your imports, collecting back duties for up to 5 years plus negligence penalties (2x-4x the duty underpayment). Gross negligence or fraud cases face penalties up to the full value of the merchandise. Always seek professional help or binding rulings for uncertain classifications.' },
      { question: 'What is a CBP binding ruling?', answer: 'A legally binding classification decision issued by US Customs and Border Protection in response to an importer\'s request. Free to request, typically issued in 30-90 days. Protects the importer from later reclassification by CBP. Published on CBP CROSS and sets precedent for similar products.' },
      { question: 'Who is responsible for correct HTS classification?', answer: 'The importer of record, regardless of who prepared the paperwork. Using a customs broker does not shift legal responsibility. Importers are required to exercise "reasonable care" in classification, which means consulting experts and maintaining documentation when uncertain.' },
      { question: 'How often do HTS codes change?', answer: 'The 10-digit US-specific codes are updated annually by USITC. The international 6-digit codes (WCO Harmonized System) are updated every 5 years. Trade remedy tariffs (Section 301, Section 232, IEEPA) are added to Chapter 99 and can change frequently — sometimes monthly.' },
      { question: 'What is the difference between HTS and Schedule B?', answer: 'HTS is used for imports into the US. Schedule B is used for exports from the US. The first 6 digits are the same (both use the WCO Harmonized System), but the last 4 digits differ. You need HTS for imports, Schedule B for exports.' },
    ],
  },
  {
    slug: 'section-301-232-ieepa-tariffs',
    title: 'Section 301 vs 232 vs IEEPA: The 3 Types of US Tariffs and When Each Applies',
    description: 'The three major legal authorities behind US tariff increases since 2018 — how Section 301 China tariffs, Section 232 national security tariffs, and IEEPA emergency tariffs actually work.',
    category: 'Trade Policy',
    updatedAt: u,
    intro: `<p>Between 2018 and 2025, the US imposed three major waves of tariffs beyond the standard HTS rates. Each used a different legal authority: Section 301 of the Trade Act of 1974 (China-specific), Section 232 of the Trade Expansion Act of 1962 (national security), and the International Emergency Economic Powers Act of 1977 (IEEPA, used for the 2025 Trump universal tariffs). Each authority has different legal requirements, appeal processes, and coverage. Understanding which applies to your imports determines your real landed cost, your exemption options, and your mitigation strategies. This guide breaks down all three.</p>`,
    sections: [
      {
        heading: 'Section 301: the China tariff framework',
        html: `<p>Section 301 of the Trade Act of 1974 authorizes the US Trade Representative (USTR) to investigate and respond to unfair foreign trade practices. It became the legal basis for the Trump administration's China tariffs starting in 2018.</p><p>Legal mechanics:</p><ul><li><strong>USTR investigates</strong> a foreign country's trade practices (in the China case, technology transfer, IP theft, and market access barriers)</li><li><strong>If violations are found,</strong> USTR can impose retaliatory tariffs</li><li><strong>Tariffs are imposed in "Lists"</strong> — List 1, List 2, List 3, List 4A each covering different product categories</li><li><strong>Rates range from 7.5% to 25%</strong> on covered goods, on top of the normal HTS rate</li></ul><p>Scope as of 2025:</p><ul><li>Covers roughly $350-$400 billion in annual Chinese imports</li><li>List 1, 2, 3 at 25%; List 4A at 7.5%</li><li>Some exclusions granted through a formal exclusion process</li></ul><p>Exclusion process:</p><ul><li><strong>USTR exclusion requests:</strong> importers could petition for exclusions for specific products not available outside China or where cost burden was excessive</li><li><strong>Most exclusions expired in 2020-2021;</strong> some renewals have been granted</li><li><strong>New exclusion request windows</strong> are opened periodically; check USTR.gov</li></ul><p>Appeals are complicated. A negative USTR decision can be challenged in the Court of International Trade (CIT) under specific grounds. Several Section 301 challenges have been filed; most have been unsuccessful at invalidating the tariffs entirely.</p>`,
      },
      {
        heading: 'Section 232: national security tariffs',
        html: `<p>Section 232 of the Trade Expansion Act of 1962 allows the President to adjust imports if the Department of Commerce determines they threaten national security. It's been used rarely but significantly since 2018.</p><p>Legal mechanics:</p><ul><li><strong>Commerce investigation:</strong> the Department of Commerce investigates whether imports threaten national security, issues a report with recommendations</li><li><strong>Presidential action:</strong> the President has 90 days to act on the recommendations, including imposing tariffs, quotas, or other remedies</li><li><strong>Proclamation:</strong> the final tariffs are set by presidential proclamation and added to Chapter 99 of the HTS</li></ul><p>Section 232 actions since 2018:</p><ul><li><strong>Steel (March 2018):</strong> 25% tariff on steel imports from most countries</li><li><strong>Aluminum (March 2018):</strong> 10% tariff on aluminum imports from most countries</li><li><strong>Derivative steel and aluminum products (2020):</strong> extended tariffs to downstream products</li></ul><p>Country-specific adjustments:</p><ul><li>Quota systems replaced tariffs for some countries (Brazil, Korea, Argentina)</li><li>Bilateral deals with EU, Japan, UK created tariff-rate quotas</li><li>Mexico and Canada exempted under USMCA</li></ul><p>Exclusion process: Commerce Department accepts product-specific exclusion requests. Exclusions are granted for products not produced in sufficient quantity in the US. The process is slow (often 6+ months) and grants roughly 50% of requests.</p>`,
      },
      {
        heading: 'IEEPA: the 2025 Trump universal tariffs',
        html: `<p>The International Emergency Economic Powers Act of 1977 (IEEPA) was traditionally used for sanctions (Iran, Russia, North Korea) rather than trade policy. In 2025, the Trump administration used it as the legal basis for sweeping universal tariffs.</p><p>Legal mechanics:</p><ul><li><strong>Presidential declaration of national emergency</strong> — required for IEEPA actions</li><li><strong>Comprehensive authority:</strong> can regulate or prohibit nearly any international transaction</li><li><strong>Judicial review:</strong> limited and courts have traditionally deferred heavily to presidential national emergency declarations</li></ul><p>The 2025 IEEPA tariffs:</p><ul><li><strong>Universal baseline:</strong> 10% on most imports from all countries (with specific exemptions)</li><li><strong>Country-specific rates:</strong> higher rates on specific countries (20% on EU, 10-25% on various others)</li><li><strong>Cumulative with existing tariffs:</strong> IEEPA tariffs stack on top of HTS general rates, Section 301, and Section 232</li></ul><p>Legal challenges:</p><ul><li>Multiple lawsuits filed arguing IEEPA does not authorize tariffs as opposed to sanctions</li><li>Court of International Trade and Federal Circuit cases pending</li><li>Supreme Court likely to address the scope of IEEPA for trade purposes</li></ul><p>The legal status of IEEPA-based tariffs is genuinely uncertain as of 2026. Importers should plan for the tariffs to remain but be aware that major court decisions could change the landscape.</p>`,
      },
      {
        heading: 'Stacking: when multiple tariffs apply',
        html: `<p>The single biggest complication in modern US imports is that multiple tariff regimes can stack on the same product. Example for a Chinese-origin steel bracket:</p><ol><li><strong>Standard HTS rate:</strong> 2.9% (Chapter 73 base metal products)</li><li><strong>Section 232 steel tariff:</strong> additional 25%</li><li><strong>Section 301 China List 1 tariff:</strong> additional 25%</li><li><strong>IEEPA 2025 universal tariff:</strong> additional 10%</li><li><strong>Total landed duty:</strong> ~62.9% of value</li></ol><p>In some cases tariffs compound multiplicatively rather than additively (though CBP typically applies them additively). Always calculate the full stack to understand the real landed cost.</p><p>Country of origin is critical. The same steel bracket from Vietnam would avoid the Section 301 and potentially part of the IEEPA tariff, making the Vietnamese-origin version dramatically cheaper despite higher base price.</p>`,
      },
      {
        heading: 'How to reduce your tariff burden',
        html: `<p>Five legal strategies importers use to minimize tariffs:</p><ol><li><strong>Classification review.</strong> Make sure you're using the correct HTS code. A slight shift can move you out of a Section 301 list or into a lower-rate subheading.</li><li><strong>Country of origin change.</strong> Shift sourcing to a country with lower total tariff burden. Vietnam, India, Mexico, and Thailand have been major beneficiaries of shifts away from China.</li><li><strong>First Sale Rule.</strong> Structure transactions so customs value is based on the first sale in a multi-tier chain, not the last. Can reduce customs value by 20-40% — see our <a href="/guide/first-sale-rule/">First Sale guide</a>.</li><li><strong>Duty Drawback.</strong> For goods re-exported or used in exported products, recover up to 99% of duties paid. See our <a href="/guide/duty-drawback/">Duty Drawback guide</a>.</li><li><strong>Foreign Trade Zones (FTZ) and bonded warehouses.</strong> Delay tariff payment until goods leave the zone. Useful for inventory management and for products that may be re-exported.</li></ol><p>Each strategy has specific requirements and documentation. Consulting a licensed customs broker or trade attorney is essential for complex import operations.</p>`,
      },
    ],
    faqs: [
      { question: 'What is Section 301?', answer: 'Section 301 of the Trade Act of 1974 allows the US Trade Representative to impose retaliatory tariffs in response to unfair foreign trade practices. It became the legal basis for the Trump administration\'s China tariffs starting in 2018, covering roughly $350-$400 billion in annual Chinese imports at rates of 7.5%-25%.' },
      { question: 'What is Section 232?', answer: 'Section 232 of the Trade Expansion Act of 1962 allows the President to adjust imports that threaten national security. Used in 2018 to impose 25% tariffs on steel and 10% tariffs on aluminum from most countries. Country-specific adjustments and exclusion processes exist.' },
      { question: 'What is IEEPA and how is it being used for tariffs?', answer: 'The International Emergency Economic Powers Act of 1977 traditionally used for sanctions. In 2025, the Trump administration used it as the legal basis for universal baseline tariffs (10% on most imports) plus country-specific rates. Legal challenges are pending; Supreme Court likely to address the scope.' },
      { question: 'Do multiple tariffs stack on top of each other?', answer: 'Yes. A Chinese-origin steel bracket can face: standard HTS rate (2.9%) + Section 232 steel tariff (25%) + Section 301 China List 1 (25%) + IEEPA universal (10%) = total ~62.9% of value. Always calculate the full stack for accurate landed cost.' },
      { question: 'Can I get exclusions from these tariffs?', answer: 'Yes, for some. Section 232 accepts product-specific exclusion requests from Commerce (slow, ~50% success rate). Section 301 had exclusion windows that opened periodically; many expired but some renewals exist. IEEPA exclusions are newer and the process is still developing. Check USTR.gov and the Federal Register.' },
      { question: 'How do I avoid these tariffs legally?', answer: 'Five strategies: verify correct HTS classification, shift country of origin (Vietnam, India, Mexico have gained from China shifts), use First Sale rule for transaction value, claim duty drawback on re-exports, and use Foreign Trade Zones for inventory management. Each has specific requirements — consult a licensed customs broker.' },
    ],
  },
  {
    slug: 'trump-tariffs-2025-who-pays',
    title: 'The 2025 Trump Tariffs: Who Actually Pays',
    description: 'The economics of the 2025 universal baseline tariffs, the pass-through to US consumers, the country-specific rates, and what Fed and academic research actually shows about tariff incidence.',
    category: 'Trade Policy',
    updatedAt: u,
    intro: `<p>The 2025 Trump tariffs represent the largest protectionist shift in US trade policy since the Smoot-Hawley Tariff Act of 1930. A 10% universal baseline tariff on most imports, combined with country-specific rates as high as 25% for some nations, has reshaped import costs across virtually every product category. The political debate frames tariffs as being "paid by" foreign exporters — the economic reality is more complicated. This guide explains who actually pays tariffs based on peer-reviewed research, the specific 2025 rate structure, and what the data shows about US consumer and business impacts.</p>`,
    sections: [
      {
        heading: 'Who legally pays tariffs: the importer of record',
        html: `<p>Legally, the US "importer of record" (usually the US company bringing goods into the country) pays the tariff to US Customs and Border Protection at the time of import. This is a straightforward fact. The tariff is collected at the port of entry and remitted to the US Treasury.</p><p>A Chinese manufacturer selling goods to a US retailer does NOT pay the tariff directly to the US government. The US retailer pays it.</p><p>The political claim "tariffs are paid by the foreign country" is wrong as a matter of legal mechanics. No foreign country has ever written a check to the US Treasury for a US tariff.</p>`,
      },
      {
        heading: 'Who economically pays: the "incidence" question',
        html: `<p>The legal payer is not necessarily the economic payer. Economic incidence depends on who ends up bearing the cost after markets adjust. Three possibilities:</p><ol><li><strong>Foreign exporters absorb the tariff</strong> by cutting their prices, keeping total US cost unchanged</li><li><strong>US importers absorb the tariff</strong> by reducing margins, keeping retail prices unchanged</li><li><strong>US consumers pay through higher prices</strong> when importers pass the cost through</li></ol><p>In practice, the split depends on market structure, competition, and product availability. Research has produced fairly consistent findings about the 2018-2019 Trump tariffs (which we have several years of data on):</p><ul><li><strong>Amiti, Redding, Weinstein (NBER 2019):</strong> found near-100% pass-through to US prices for Section 301 China tariffs. Foreign exporters did not cut prices.</li><li><strong>Fajgelbaum et al. (Quarterly Journal of Economics 2020):</strong> estimated US consumers and firms bore virtually all the tariff cost, with about $51 billion in annual welfare losses.</li><li><strong>Cavallo et al. (AER 2021):</strong> documented almost complete pass-through to retail prices for affected goods.</li></ul><p>The conclusion from this research: <strong>US consumers and businesses pay the tariffs, not foreign exporters.</strong> This is the mainstream academic finding, not a politically contested claim.</p>`,
      },
      {
        heading: 'The 2025 tariff structure',
        html: `<p>The 2025 Trump tariffs (imposed via IEEPA starting April 2025) have three layers:</p><ol><li><strong>Universal baseline tariff: 10%</strong> on imports from most countries</li><li><strong>Country-specific rates:</strong> higher rates on selected trading partners:<ul><li>China: additional 10-25% on top of existing Section 301 tariffs (effective combined rates of 35-50%+ for many goods)</li><li>European Union: additional 20% (effective total higher with stacking)</li><li>Vietnam: 46% country-specific rate initially, later negotiated down</li><li>Japan, South Korea: various rates 10-24%</li><li>Other countries: scaled rates based on "reciprocal" calculation methodology</li></ul></li><li><strong>Product-specific exclusions:</strong> limited exemptions for pharmaceuticals, semiconductors (some), and certain critical minerals</li></ol><p>These stack with existing Section 301 and Section 232 tariffs. A Chinese-origin electronic component faces: 0-5% base HTS rate + 25% Section 301 + 10-25% IEEPA = 35-55% total duty.</p>`,
      },
      {
        heading: 'Impact on US consumer prices',
        html: `<p>Federal Reserve research (Flaaen, Hortaçsu, Tintelnot 2019) and Fed Board analysis of 2018 tariffs found:</p><ul><li><strong>Washing machines (20-50% tariff):</strong> US prices rose 11.5% in the first year</li><li><strong>Solar panels (30% tariff):</strong> US prices rose 8-10%</li><li><strong>Steel and aluminum:</strong> US prices rose 9-14%</li><li><strong>Broader consumer goods from China (10-25% tariffs):</strong> mixed pass-through, with retailers absorbing some costs during inflation-sensitive periods</li></ul><p>Early analysis of 2025 tariffs (limited data as of early 2026) suggests similar patterns:</p><ul><li>Apparel and footwear prices rose 5-12% within 6 months of implementation</li><li>Electronics and appliances rose 4-8%</li><li>Automotive parts rose 6-10%</li><li>Overall Consumer Price Index impact estimated at 0.5-1.0% additional inflation</li></ul><p>For a typical US household spending $3,000/month on consumer goods, tariff-driven price increases translate to roughly $15-$30/month in added costs — about $180-$360/year. Higher earners and families with more imported-goods consumption bear proportionally more cost.</p>`,
      },
      {
        heading: 'The "revenue" argument vs economic reality',
        html: `<p>Defenders of tariffs sometimes point to the revenue collected as evidence they "work." The numbers are real: US tariff revenue rose from about $35 billion per year pre-2018 to over $80 billion per year during peak Section 301 collection. With 2025 IEEPA universal tariffs, projected revenue exceeds $200 billion annually.</p><p>However, this revenue represents a transfer from US businesses and consumers to the federal government — not from foreign entities. In economic terms, it's an indirect consumption tax with distortions rather than a payment extracted from trading partners.</p><p>The distortions matter:</p><ul><li><strong>Deadweight loss:</strong> tariffs reduce total economic activity by raising prices above the competitive level. Estimates of 2018-2019 tariffs: $7-11 billion per year in deadweight loss.</li><li><strong>Retaliation:</strong> foreign countries impose counter-tariffs on US exports. US soybean exports to China dropped 75% in 2018; agricultural support programs partially offset the damage at taxpayer expense.</li><li><strong>Supply chain disruption:</strong> firms invest in changing supply chains to avoid tariffs. These costs are real even when the tariff revenue is collected.</li><li><strong>Input costs for US manufacturers:</strong> roughly half of US imports are intermediate goods used in US production. Tariffs on these make US-made products more expensive, reducing US export competitiveness.</li></ul>`,
      },
      {
        heading: 'What importers can actually do',
        html: `<p>Given that tariffs are largely paid by US businesses and consumers, importers have strong incentives to minimize the impact. Five practical responses:</p><ol><li><strong>Diversify sourcing.</strong> Shift production from high-tariff countries to lower-tariff alternatives. Vietnam, India, Mexico, Thailand, and Indonesia have been major beneficiaries.</li><li><strong>Renegotiate supplier contracts.</strong> Ask foreign suppliers to share the tariff burden by reducing their prices. Success varies by bargaining power and product alternatives.</li><li><strong>Pursue classification and valuation optimizations.</strong> Verify HTS codes, consider First Sale Rule, use tariff engineering (modifying products to change classification).</li><li><strong>Pass through to customers strategically.</strong> For price-inelastic goods, full pass-through is possible. For competitive goods, partial absorption may be necessary.</li><li><strong>Use Foreign Trade Zones and duty drawback</strong> where applicable.</li></ol><p>Each of these has documentation and compliance requirements. See our <a href="/guide/first-sale-rule/">First Sale Rule</a> and <a href="/guide/duty-drawback/">Duty Drawback</a> guides for the mechanics.</p>`,
      },
    ],
    faqs: [
      { question: 'Who actually pays US tariffs?', answer: 'Legally, the US importer of record pays the tariff to US Customs. Economically, research shows that nearly all the cost is passed through to US consumers and businesses via higher prices. Foreign exporters do not absorb the tariffs by cutting their prices — peer-reviewed studies of 2018-2019 tariffs found near-100% pass-through to US prices.' },
      { question: 'How much are the 2025 Trump tariffs?', answer: '10% universal baseline on most imports, plus country-specific rates of 10-46% on selected countries. These stack with existing Section 301 (China, 7.5-25%) and Section 232 (steel/aluminum, 10-25%) tariffs. Total effective rates on Chinese goods commonly reach 35-55%.' },
      { question: 'How much are tariffs raising consumer prices?', answer: 'Early analysis of 2025 tariffs estimates 0.5-1.0% additional CPI inflation. For a typical household spending $3,000/month on consumer goods, that\'s $15-$30/month or $180-$360/year. Specific product categories like apparel, electronics, and appliances have seen 5-12% price increases.' },
      { question: 'Why do politicians say foreign countries pay the tariffs?', answer: 'As a political claim, not an accurate description of economic mechanics. Legally, the US importer writes the check. Economically, the cost is passed through to US consumers. No foreign country has ever paid a US tariff directly to the US Treasury. The "foreign countries pay" framing is inconsistent with both legal mechanics and academic research.' },
      { question: 'How can I avoid or reduce tariff costs?', answer: 'Five strategies: diversify sourcing to lower-tariff countries, renegotiate with suppliers to share the burden, optimize HTS classification, use First Sale Rule for transaction valuation, and claim duty drawback on re-exported goods. Consult a licensed customs broker for complex cases.' },
      { question: 'Will the 2025 tariffs survive court challenges?', answer: 'Uncertain as of 2026. Multiple lawsuits argue that IEEPA does not authorize tariffs as opposed to sanctions. The Court of International Trade and Federal Circuit have cases pending. The Supreme Court will likely address the scope of IEEPA for trade purposes. Importers should plan for tariffs to remain but be aware of potential legal changes.' },
    ],
  },
  {
    slug: 'first-sale-rule',
    title: 'First Sale Rule: How Importers Legally Cut Tariff Costs 20-40%',
    description: 'The First Sale Rule explained: how multi-tier transactions allow importers to base customs value on the first sale instead of the final, with CBP documentation requirements and case law.',
    category: 'Duty Reduction',
    updatedAt: u,
    intro: `<p>The First Sale Rule is one of the most powerful and least-known legal tariff reduction strategies available to US importers. It allows the customs value of imported goods to be based on an earlier sale in a multi-tier transaction chain, rather than the final sale to the US importer. Properly structured, it reduces the dutiable value by 20-40% in many sourcing arrangements, directly lowering tariff costs. The rule has been validated by CBP and the courts for over 30 years, but requires careful documentation and transaction structure. This guide explains the legal basis, how to qualify, the documentation CBP requires, and the case law importers should know.</p>`,
    sections: [
      {
        heading: 'The legal basis: Nissho Iwai',
        html: `<p>The First Sale Rule comes from a 1992 Federal Circuit case, <em>Nissho Iwai American Corp v. United States</em>. Before this case, CBP treated the final sale to the US importer as the default dutiable value — meaning duty was calculated on the full markup.</p><p>Nissho Iwai involved a Japanese trading company purchasing machinery from Japanese manufacturers and reselling to US buyers. The court held that the <strong>first sale in a bona fide arm's length transaction destined for the US</strong> could be used as the customs value, not the second sale. This established the rule that has been used ever since.</p><p>CBP codified the rule in its 1996 informed compliance publication. Since then, thousands of importers have used First Sale, and the rule has been repeatedly upheld in court challenges.</p>`,
      },
      {
        heading: 'How First Sale works in practice',
        html: `<p>Example: A Chinese manufacturer sells products to a Hong Kong trading company for $60. The Hong Kong trader marks up 40% and sells to a US importer for $100. Normal customs valuation would use the $100 as the dutiable value. First Sale allows the $60 to be used instead.</p><p>On a 25% tariff rate:</p><ul><li><strong>Without First Sale:</strong> duty = $100 × 25% = $25</li><li><strong>With First Sale:</strong> duty = $60 × 25% = $15</li><li><strong>Savings:</strong> $10 per unit, or 40% of the duty</li></ul><p>For high-value imports with multiple tiers (common in apparel, electronics, and commodities), the savings can be enormous. A company importing $10 million annually can often save $200,000-$1 million in duties using First Sale.</p>`,
      },
      {
        heading: 'The three required elements',
        html: `<p>For First Sale to be valid, three elements must be met:</p><ol><li><strong>The first sale must be a bona fide sale.</strong> Not a transfer within a corporate family, not a consignment, not a commissionaire arrangement. It must be an actual arm's length transaction with legal title transferring.</li><li><strong>The first sale must be at arm's length.</strong> The price must reflect fair market value between unrelated (or properly-priced related) parties. Evidence of independent negotiation is key.</li><li><strong>The goods must be destined for the US at the time of the first sale.</strong> This is the critical requirement. The factory must know, at the time of the first sale, that the goods are intended for export to the US.</li></ol><p>The "destined for the US" requirement is where most First Sale claims fail. If the first sale could have been sold to any market, it doesn't qualify. Documentation must show the US destination was known from the start.</p>`,
      },
      {
        heading: 'Documentation CBP requires',
        html: `<p>CBP will accept First Sale valuations only if the importer can prove all three required elements. Typical documentation package:</p><ul><li><strong>Purchase orders from all tiers in the transaction chain.</strong> The US importer's order, the middleman's order to the factory, and any earlier tiers.</li><li><strong>Invoices from all tiers.</strong> Showing prices, payment terms, and destination.</li><li><strong>Proof of payment</strong> between each tier (wire transfer records, bank statements).</li><li><strong>Contracts and agreements</strong> establishing the business relationship and terms.</li><li><strong>Shipping documents</strong> showing the goods moving from origin to the US.</li><li><strong>Evidence of US destination knowledge at the factory level.</strong> This can include the US importer being named on early documents, specific US requirements (labeling, certifications, packaging) built into the order, etc.</li></ul><p>CBP is increasingly rigorous about First Sale documentation. Audits in 2020-2024 have resulted in some major reassessments where importers couldn't produce adequate documentation. Maintain a dedicated First Sale documentation binder for each transaction.</p>`,
      },
      {
        heading: 'Common structures that work',
        html: `<p>Three transaction structures commonly qualify for First Sale:</p><p><strong>Structure 1: Factory → Middleman → US Importer</strong></p><ul><li>Factory sells to middleman at first-sale price</li><li>Middleman acts as buying agent, exporter, or reseller</li><li>Middleman sells to US importer at marked-up price</li><li>US importer qualifies for First Sale valuation based on the factory price</li></ul><p><strong>Structure 2: Multiple intermediate tiers</strong></p><ul><li>Factory → Agent in origin country → Trading company → US importer</li><li>Each tier adds markup</li><li>US importer can claim First Sale based on the earliest qualifying sale</li></ul><p><strong>Structure 3: Factory → Branch office → US parent</strong></p><ul><li>Factory in one country sells to a related trading branch</li><li>Branch sells to US parent company</li><li>If properly documented as arm's-length related-party transaction, First Sale valuation based on factory price is possible</li><li>Related-party transactions require additional documentation proving arm's-length pricing</li></ul>`,
      },
      {
        heading: 'Common mistakes and pitfalls',
        html: `<p>Five reasons First Sale claims get rejected:</p><ol><li><strong>Inadequate "destined for US" documentation.</strong> If the goods could have been sold to any market, First Sale doesn't apply. Documentation must clearly show US destination from the first sale.</li><li><strong>Commissionaire arrangements treated as sales.</strong> If the middleman is technically a commissionaire (earning commission on a sale between the factory and buyer), the commission is a separate service and the underlying sale is the dutiable one.</li><li><strong>Related-party pricing issues.</strong> If the middleman and importer are related, CBP will scrutinize whether the markup reflects arm's length pricing. Documentation of comparable third-party transactions is needed.</li><li><strong>Missing or incomplete documentation.</strong> Audits 5+ years after the transaction require the same documentation be produced. Keep records organized.</li><li><strong>Inconsistent treatment.</strong> Claiming First Sale on some imports but not others without clear reason triggers CBP scrutiny.</li></ol><p>Importers using First Sale should conduct internal reviews annually and consider having a customs attorney validate their documentation protocols.</p>`,
      },
      {
        heading: 'When First Sale is worth pursuing',
        html: `<p>Five scenarios where First Sale makes the most sense:</p><ul><li><strong>High tariff products</strong> (Section 301, Section 232, or IEEPA-affected goods). The higher the tariff rate, the greater the savings.</li><li><strong>High markup between first and last sale.</strong> If middlemen add 30%+ markup, First Sale savings are substantial.</li><li><strong>Stable supplier relationships.</strong> First Sale requires cooperation from multiple parties in the transaction chain. Stable relationships make documentation easier.</li><li><strong>High volume imports.</strong> The setup cost (documentation, possibly legal fees) is fixed. High volume amortizes this cost.</li><li><strong>Direct factory-to-US transaction restructuring.</strong> Some importers restructure to add a middleman specifically to qualify for First Sale, where savings exceed the cost of the restructure.</li></ul><p>Importers with less than $1 million in annual imports may find the First Sale documentation burden exceeds the savings. Above $5 million in imports, First Sale is almost always worth the effort.</p>`,
      },
    ],
    faqs: [
      { question: 'What is the First Sale Rule?', answer: 'A customs valuation method that allows importers to base the dutiable value on an earlier sale in a multi-tier transaction chain, rather than the final sale to the US importer. Established in the 1992 Federal Circuit case Nissho Iwai and codified by CBP. Can reduce dutiable value 20-40%.' },
      { question: 'How does First Sale reduce tariff costs?', answer: 'By basing duty on the lower first-sale price rather than the higher final-sale price. Example: factory sells to middleman for $60, middleman sells to US importer for $100. Without First Sale, duty on $100. With First Sale, duty on $60. On a 25% tariff, savings of $10 per unit or 40% of the duty.' },
      { question: 'What documentation does CBP require for First Sale?', answer: 'Purchase orders and invoices from all tiers in the transaction chain, proof of payment at each tier, contracts establishing relationships, shipping documents, and critically, evidence that the goods were destined for the US at the time of the first sale. The "US destination" documentation is where most First Sale claims fail.' },
      { question: 'Can I use First Sale with related companies?', answer: 'Yes, but with additional requirements. Related-party transactions must demonstrate arm\'s length pricing — the price between related parties must reflect what unrelated parties would charge. This typically requires documentation of comparable third-party transactions or other evidence of fair market value.' },
      { question: 'What products qualify for First Sale?', answer: 'All imported products in principle. The rule applies to customs valuation, not specific product categories. In practice, First Sale is most valuable for high-tariff goods (Section 301, 232, IEEPA) and for products with significant markup between first and final sale.' },
      { question: 'Is First Sale legal?', answer: 'Yes. The rule was established by the 1992 Federal Circuit case Nissho Iwai American Corp v. United States, codified by CBP in 1996, and has been used by thousands of importers for over 30 years. It is explicitly recognized in CBP regulations and the Customs Modernization Act.' },
      { question: 'When should I NOT use First Sale?', answer: 'When total imports are under $1 million annually (documentation burden may exceed savings), when the markup between first and last sale is small, when relationships with middlemen are unstable, or when adequate "US destination" documentation cannot be produced. Also avoid if your supply chain uses commissionaires rather than actual sellers — commissionaire arrangements don\'t qualify.' },
    ],
  },
  {
    slug: 'duty-drawback',
    title: 'Duty Drawback: Recovering Tariffs on Re-Exported Goods',
    description: 'How to recover up to 99% of tariffs paid on imported goods that are later exported — manufacturing drawback, unused merchandise drawback, and the substitution rules.',
    category: 'Duty Reduction',
    updatedAt: u,
    intro: `<p>Duty drawback is the most underused legal tariff reduction program in the United States. It allows importers to recover up to 99% of duties paid on goods that are later exported, either directly or after being used in US manufacturing. The program has existed since 1789 (yes, signed by George Washington) and is specifically designed to avoid penalizing US exporters for using imported inputs. Despite saving US businesses billions of dollars annually, most eligible importers never claim drawback because of administrative complexity and unfamiliarity with the program. This guide explains how drawback works, the three main types, the documentation required, and when it's worth pursuing.</p>`,
    sections: [
      {
        heading: 'How duty drawback works',
        html: `<p>Duty drawback allows US Customs and Border Protection to refund up to 99% of duties paid on imported goods, under specific circumstances where those goods (or products made from them) are later exported from the US. The 1% that is NOT refunded covers CBP's administrative costs.</p><p>The program was expanded and modernized by the Trade Facilitation and Trade Enforcement Act of 2015 (TFTEA), which dramatically simplified the rules and expanded eligibility. Under modern TFTEA drawback:</p><ul><li><strong>Time window:</strong> you have 5 years from the date of import to file a drawback claim</li><li><strong>Export window:</strong> the export must occur within 5 years of the import</li><li><strong>Recovery amount:</strong> up to 99% of duties, fees, and taxes paid on the import (including HTS general rate, Section 301, Section 232, and IEEPA tariffs)</li><li><strong>Filing:</strong> claims are filed electronically through CBP's ACE system</li></ul><p>The program applies to virtually any import duty or fee, with limited exceptions. Drawback is fully compatible with First Sale Rule — you can use both strategies on the same transaction.</p>`,
      },
      {
        heading: 'Type 1: Unused merchandise drawback',
        html: `<p>The simplest form of drawback. If you import goods, don't use them, and later export them, you can recover 99% of the duties. Requirements:</p><ul><li>The exported merchandise must be the same as the imported merchandise (unused, unchanged)</li><li>Minor handling like inspection, repackaging, or testing is allowed</li><li>Export must occur within 5 years of import</li></ul><p>Common situations where unused merchandise drawback applies:</p><ul><li><strong>Excess inventory sold abroad:</strong> products that didn't sell in the US and were exported to foreign markets</li><li><strong>Returns and defective goods:</strong> imported goods that were returned to foreign suppliers</li><li><strong>Re-exports to fulfill foreign orders</strong></li><li><strong>Goods imported speculatively that didn't find buyers</strong></li></ul><p>Documentation: import records showing duties paid, export records showing the same goods leaving the US, and a chain of custody documentation proving the exported goods are the same as the imported goods.</p>`,
      },
      {
        heading: 'Type 2: Manufacturing drawback',
        html: `<p>The most common form of drawback. If you import raw materials, components, or ingredients, use them in US manufacturing, and export the finished product, you can recover 99% of the duties paid on the inputs. Requirements:</p><ul><li>The imported merchandise must be used in manufacturing in the US</li><li>The finished product must be exported within 5 years of the import</li><li>Records must link the specific imported materials to the specific exported finished products</li></ul><p>Manufacturing drawback is the backbone of US export competitiveness for industries using imported inputs. Major users:</p><ul><li><strong>Automotive industry:</strong> imported parts used in US vehicles exported to foreign markets</li><li><strong>Chemical and pharmaceutical manufacturing:</strong> imported ingredients in US-made finished products for export</li><li><strong>Electronics assembly:</strong> imported components in US-assembled products for export</li><li><strong>Textiles and apparel:</strong> imported fabrics in US-made garments for export</li></ul><p>The tracing requirement (linking specific imports to specific exports) is the biggest administrative burden of manufacturing drawback. Modern ERP systems and drawback specialist software can automate much of this, but small manufacturers often find the complexity prohibitive.</p>`,
      },
      {
        heading: 'Type 3: Substitution drawback (the TFTEA simplification)',
        html: `<p>Before TFTEA, drawback required exact tracing — a specific imported item had to be tied to a specific exported item. This was administratively impossible for many manufacturers using commodity inputs.</p><p>TFTEA substitution drawback simplifies this by allowing "same 8-digit HTS code" substitution. Under the rule, you can claim drawback if:</p><ul><li>You imported goods classified under a specific 8-digit HTS code</li><li>You exported (or used in manufacturing exported products) goods classified under the same 8-digit HTS code</li><li>The import and export occurred within the 5-year window</li><li>The exported goods don't need to be the same physical items as the imported goods — just the same HTS classification</li></ul><p>Example: you import electronic capacitors under HTS 8532.25.00 and export capacitors under the same HTS code, not necessarily the ones you imported. You can claim drawback on the imported duties.</p><p>This dramatically simplifies drawback for commodity-like imports. Before TFTEA, many eligible importers couldn't claim drawback because they couldn't trace specific units. TFTEA substitution opened the door to billions of dollars in additional drawback claims.</p>`,
      },
      {
        heading: 'Documentation requirements',
        html: `<p>To successfully claim drawback, maintain records of:</p><ul><li><strong>Original import entries</strong> (CBP Form 7501 or ACE equivalent) showing duties paid</li><li><strong>Proof of payment</strong> to CBP</li><li><strong>Manufacturing records</strong> (for manufacturing drawback) linking imported materials to finished products</li><li><strong>Export records:</strong> shipper's export declaration, commercial invoice, bill of lading, proof of shipment</li><li><strong>Bill of materials</strong> showing the quantity of imported inputs used per unit of exported output (for manufacturing drawback)</li><li><strong>Inventory records</strong> demonstrating the chain of custody and timing</li></ul><p>The documentation must be maintained for at least 5 years after the drawback claim is filed (on top of the 5-year filing window). Practically, this means keeping records for 10 years.</p><p>CBP audits drawback claims. The penalty for a fraudulent or unsupported claim is repayment of the drawback plus penalties up to 2x the amount claimed. Most importers use a drawback specialist or customs broker for claim preparation.</p>`,
      },
      {
        heading: 'When drawback is worth pursuing',
        html: `<p>Drawback makes financial sense when:</p><ul><li><strong>Annual exports exceed $1 million</strong> and include imported inputs</li><li><strong>Imports face high tariff rates</strong> (Section 301 China goods, Section 232 steel/aluminum, IEEPA universal tariffs)</li><li><strong>Your supply chain is stable enough</strong> to maintain tracing records</li><li><strong>You have dedicated trade compliance or can outsource to a drawback specialist</strong></li></ul><p>Practical numbers:</p><ul><li>A manufacturer exporting $10 million annually with $1 million in imported inputs at 25% Section 301 tariff could recover up to $247,500 per year in drawback</li><li>The setup cost for drawback is typically $10,000-$50,000 for initial implementation, plus 5-10% of drawback recovered as ongoing service fees</li><li>Net savings on the $247,500 example: $200,000-$235,000 per year, fully recurring</li></ul><p>Drawback specialists (companies that do nothing but file drawback claims for importers) are common for medium and large manufacturers. They typically charge a percentage of recoveries. For smaller importers, a customs broker with drawback experience is a more cost-effective option.</p>`,
      },
    ],
    faqs: [
      { question: 'What is duty drawback?', answer: 'A US Customs program that refunds up to 99% of duties, fees, and taxes paid on imported goods when those goods (or products made from them) are later exported. Applied to about $3 billion in recoveries annually. Fully compatible with other tariff reduction strategies like First Sale Rule.' },
      { question: 'How much of my duties can I recover through drawback?', answer: 'Up to 99%. The 1% that is NOT refunded covers CBP\'s administrative costs. The refund includes all duties, fees, and taxes paid at import, including HTS general rate, Section 301, Section 232, and IEEPA tariffs.' },
      { question: 'What types of duty drawback exist?', answer: 'Three main types: (1) Unused merchandise drawback for goods imported and later exported without use, (2) Manufacturing drawback for imported inputs used in US manufacturing of exported products, (3) Substitution drawback (under TFTEA) allowing "same 8-digit HTS code" substitution without requiring exact tracing.' },
      { question: 'How long do I have to file a drawback claim?', answer: '5 years from the date of import. Both the export and the drawback claim must occur within this 5-year window. TFTEA simplified and extended the timeline compared to pre-2015 rules.' },
      { question: 'Who should pursue duty drawback?', answer: 'Manufacturers exporting $1 million or more annually with imported inputs, particularly from high-tariff sources like China (Section 301) or steel/aluminum (Section 232). Setup costs are $10,000-$50,000 for initial implementation; ongoing recovery commonly exceeds $200,000-$1 million annually for medium-size manufacturers.' },
      { question: 'Does drawback work with Section 301 China tariffs?', answer: 'Yes. Drawback applies to all duties, fees, and taxes paid at import, including Section 301 trade remedy tariffs. A manufacturer importing Chinese components at 25% Section 301 tariff and exporting the finished product can recover up to 99% of those duties through manufacturing drawback.' },
      { question: 'What documentation do I need for drawback?', answer: 'Import entries (CBP Form 7501), proof of duty payment, manufacturing records linking imports to finished products (for manufacturing drawback), bill of materials, export records (shipper\'s export declaration, commercial invoice, bill of lading), and inventory records. Must be maintained for 10 years (5 years to file + 5 years after filing).' },
    ],
  },
];

export function getAllGuides(): Guide[] {
  return guides;
}

export function getGuideBySlug(slug: string): Guide | undefined {
  return guides.find((g) => g.slug === slug);
}
