/**
 * US state trade data — 50 states + DC.
 * Sources: US Census Bureau Foreign Trade Statistics, USITC DataWeb, Port Authority data.
 * Each entry: slug, name, code, major ports, top trade partners, import/export context.
 */

export interface StateTradeData {
  slug: string;
  name: string;
  code: string;
  majorPorts: string[];
  topTradePartners: string[];
  topImports: string[];
  topExports: string[];
  importVolume: string;   // human-readable, e.g. "$450B annually"
  exportVolume: string;
  tradeHighlight: string; // one-liner insight
  overview: string;       // 2-3 sentence overview paragraph
}

export const states: StateTradeData[] = [
  {
    slug: 'alabama', name: 'Alabama', code: 'AL',
    majorPorts: ['Port of Mobile'],
    topTradePartners: ['Germany', 'China', 'Canada', 'South Korea', 'Japan'],
    topImports: ['Automobiles', 'Iron & steel', 'Machinery', 'Plastics', 'Electrical equipment'],
    topExports: ['Automobiles', 'Coal', 'Aerospace parts', 'Iron & steel', 'Paper products'],
    importVolume: '$24B annually', exportVolume: '$22B annually',
    tradeHighlight: 'Home to Mercedes-Benz, Honda, Hyundai, and Mazda-Toyota assembly plants — a major auto import/export hub.',
    overview: 'Alabama is a major automotive manufacturing state with four international auto assembly plants. The Port of Mobile on the Gulf Coast handles steel, lumber, coal, and containerized cargo, serving as a gateway for imports destined for the southeastern US.',
  },
  {
    slug: 'alaska', name: 'Alaska', code: 'AK',
    majorPorts: ['Port of Anchorage', 'Port of Dutch Harbor', 'Port of Valdez'],
    topTradePartners: ['Japan', 'South Korea', 'China', 'Canada', 'Taiwan'],
    topImports: ['Mineral fuels', 'Machinery', 'Vehicles', 'Iron & steel', 'Fish & seafood'],
    topExports: ['Mineral fuels (crude oil)', 'Seafood', 'Zinc ores', 'Gold', 'Fertilizers'],
    importVolume: '$3.5B annually', exportVolume: '$5.5B annually',
    tradeHighlight: 'Alaska exports more than it imports — crude oil and seafood dominate outbound trade.',
    overview: 'Alaska\'s trade is dominated by natural resources. Crude oil from the North Slope flows through the Trans-Alaska Pipeline to Valdez for export. Dutch Harbor is the #1 US fishing port by volume, and the state is a major exporter of wild-caught seafood to Asian markets.',
  },
  {
    slug: 'arizona', name: 'Arizona', code: 'AZ',
    majorPorts: ['Nogales Port of Entry', 'San Luis Port of Entry'],
    topTradePartners: ['Mexico', 'China', 'Canada', 'Japan', 'Germany'],
    topImports: ['Fresh produce', 'Vehicles', 'Electrical machinery', 'Optical instruments', 'Copper'],
    topExports: ['Semiconductors', 'Aerospace products', 'Copper', 'Optical instruments', 'Vehicles'],
    importVolume: '$26B annually', exportVolume: '$25B annually',
    tradeHighlight: 'Nogales handles 60% of all Mexican fresh produce entering the US during winter months.',
    overview: 'Arizona sits at the crossroads of US-Mexico trade. The Nogales Port of Entry is the primary gateway for Mexican fruits and vegetables. The state is also a semiconductor manufacturing hub with TSMC and Intel fabs driving high-tech exports.',
  },
  {
    slug: 'arkansas', name: 'Arkansas', code: 'AR',
    majorPorts: ['Little Rock Port Authority', 'Port of Pine Bluff'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Japan', 'France'],
    topImports: ['Machinery', 'Vehicles', 'Iron & steel', 'Plastics', 'Electrical equipment'],
    topExports: ['Aircraft parts', 'Soybeans', 'Rice', 'Poultry', 'Iron & steel'],
    importVolume: '$8B annually', exportVolume: '$7B annually',
    tradeHighlight: 'Headquarters of Walmart, Tyson Foods, and Dillard\'s — Arkansas\'s imports reflect massive retail supply chains.',
    overview: 'Arkansas is an agricultural powerhouse and home to Walmart\'s global headquarters. Rice and soybean exports flow through Mississippi River ports, while Walmart\'s supply chain drives substantial container imports from Asia through West Coast ports.',
  },
  {
    slug: 'california', name: 'California', code: 'CA',
    majorPorts: ['Port of Los Angeles', 'Port of Long Beach', 'Port of Oakland', 'Port of San Diego'],
    topTradePartners: ['China', 'Mexico', 'Japan', 'South Korea', 'Taiwan'],
    topImports: ['Electronics', 'Vehicles', 'Machinery', 'Apparel', 'Furniture'],
    topExports: ['Computers & electronics', 'Transportation equipment', 'Chemicals', 'Agricultural products', 'Machinery'],
    importVolume: '$450B annually', exportVolume: '$175B annually',
    tradeHighlight: 'The Port of Los Angeles and Port of Long Beach together handle 40% of all US containerized imports.',
    overview: 'California is the largest trading state in the US by a wide margin. The San Pedro Bay port complex (LA + Long Beach) is the busiest in the Western Hemisphere, processing goods from thousands of trans-Pacific container ships annually. The state\'s tech industry drives semiconductor and electronics trade, while the Central Valley exports $20B+ in agricultural products.',
  },
  {
    slug: 'colorado', name: 'Colorado', code: 'CO',
    majorPorts: ['Denver International Airport (air cargo)', 'Colorado Springs'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Germany', 'Japan'],
    topImports: ['Electronics', 'Machinery', 'Vehicles', 'Optical instruments', 'Beverages'],
    topExports: ['Meat', 'Semiconductors', 'Medical instruments', 'Aerospace parts', 'Beverages'],
    importVolume: '$12B annually', exportVolume: '$9B annually',
    tradeHighlight: 'Colorado\'s aerospace and defense sector drives high-value tech exports.',
    overview: 'As a landlocked state, Colorado relies on air cargo and rail connections for international trade. The state has a strong aerospace and defense sector, with companies like Lockheed Martin and Ball Aerospace. Denver International Airport handles significant air freight, and Colorado is a major beef exporter.',
  },
  {
    slug: 'connecticut', name: 'Connecticut', code: 'CT',
    majorPorts: ['Port of New Haven', 'Port of Bridgeport'],
    topTradePartners: ['France', 'Canada', 'Germany', 'United Kingdom', 'China'],
    topImports: ['Machinery', 'Pharmaceuticals', 'Vehicles', 'Aircraft parts', 'Electrical equipment'],
    topExports: ['Aircraft engines (Pratt & Whitney)', 'Helicopters (Sikorsky)', 'Submarines', 'Pharmaceuticals', 'Machinery'],
    importVolume: '$18B annually', exportVolume: '$16B annually',
    tradeHighlight: 'Connecticut exports more aircraft engines than any other state — Pratt & Whitney is headquartered in East Hartford.',
    overview: 'Connecticut is a defense and aerospace manufacturing powerhouse. Pratt & Whitney jet engines, Sikorsky helicopters, and Electric Boat submarines are major exports. The state\'s financial services sector also drives imports of specialized technology and professional equipment.',
  },
  {
    slug: 'delaware', name: 'Delaware', code: 'DE',
    majorPorts: ['Port of Wilmington'],
    topTradePartners: ['United Kingdom', 'India', 'China', 'Germany', 'Canada'],
    topImports: ['Chemicals', 'Vehicles', 'Petroleum products', 'Bananas & fresh fruit', 'Machinery'],
    topExports: ['Chemicals', 'Pharmaceuticals', 'Plastics', 'Vehicles', 'Scientific instruments'],
    importVolume: '$12B annually', exportVolume: '$5B annually',
    tradeHighlight: 'The Port of Wilmington is the top US port for fresh fruit imports, handling 70% of East Coast banana imports.',
    overview: 'Delaware\'s Port of Wilmington is the largest fresh fruit port on the East Coast, with major Chiquita and Dole facilities. The state\'s chemical industry — anchored by DuPont\'s historic presence — drives both imports of raw materials and exports of specialty chemicals and pharmaceuticals.',
  },
  {
    slug: 'florida', name: 'Florida', code: 'FL',
    majorPorts: ['PortMiami', 'Port Everglades', 'Port of Jacksonville', 'Port Tampa Bay'],
    topTradePartners: ['Brazil', 'Colombia', 'China', 'Mexico', 'Japan'],
    topImports: ['Electronics', 'Vehicles', 'Petroleum', 'Machinery', 'Pharmaceuticals'],
    topExports: ['Civilian aircraft', 'Phosphates', 'Telecommunications equipment', 'Medical instruments', 'Citrus'],
    importVolume: '$95B annually', exportVolume: '$60B annually',
    tradeHighlight: 'PortMiami calls itself the "Cargo Gateway of the Americas" — it handles more trade with Latin America than any other US port.',
    overview: 'Florida is the primary US trade gateway to Latin America and the Caribbean. PortMiami and Port Everglades handle massive container volumes from Brazil, Colombia, and Central America. The state\'s diverse economy includes aerospace (Cape Canaveral), phosphate mining, citrus agriculture, and a growing tech sector.',
  },
  {
    slug: 'georgia', name: 'Georgia', code: 'GA',
    majorPorts: ['Port of Savannah', 'Port of Brunswick'],
    topTradePartners: ['China', 'Germany', 'Canada', 'South Korea', 'Japan'],
    topImports: ['Vehicles', 'Machinery', 'Electronics', 'Furniture', 'Plastics'],
    topExports: ['Civilian aircraft (Gulfstream)', 'Vehicles', 'Wood pulp', 'Poultry', 'Cotton'],
    importVolume: '$95B annually', exportVolume: '$42B annually',
    tradeHighlight: 'The Port of Savannah is the fastest-growing major US container port and 3rd busiest nationally.',
    overview: 'Georgia\'s Port of Savannah has grown into one of America\'s most important container ports, with massive expansion projects adding capacity. The port\'s inland connections via I-16 and I-95 serve the entire southeastern US. Georgia also hosts Kia and major distribution centers for Home Depot, Walmart, and Amazon.',
  },
  {
    slug: 'hawaii', name: 'Hawaii', code: 'HI',
    majorPorts: ['Port of Honolulu', 'Barbers Point Harbor'],
    topTradePartners: ['Singapore', 'Japan', 'South Korea', 'Australia', 'China'],
    topImports: ['Petroleum products', 'Vehicles', 'Machinery', 'Food products', 'Building materials'],
    topExports: ['Petroleum products (re-exports)', 'Food products', 'Transportation equipment', 'Machinery', 'Coffee'],
    importVolume: '$4B annually', exportVolume: '$1.5B annually',
    tradeHighlight: 'Hawaii imports roughly 85% of its food, making it heavily dependent on shipping from the mainland and Asia.',
    overview: 'Hawaii\'s island geography makes it uniquely trade-dependent. Nearly all consumer goods, fuel, and food arrive by ship. The Jones Act requires domestic shipping between US ports to use US-flagged vessels, significantly increasing costs. Honolulu also serves as a Pacific refueling and transshipment hub.',
  },
  {
    slug: 'idaho', name: 'Idaho', code: 'ID',
    majorPorts: ['Lewiston-Clarkston (inland river port)'],
    topTradePartners: ['Canada', 'Singapore', 'Taiwan', 'China', 'Mexico'],
    topImports: ['Machinery', 'Electronics', 'Vehicles', 'Fertilizers', 'Plastics'],
    topExports: ['Semiconductors (Micron)', 'Agricultural products', 'Dairy', 'Potatoes', 'Lumber'],
    importVolume: '$5B annually', exportVolume: '$5B annually',
    tradeHighlight: 'Micron Technology in Boise makes Idaho a surprising semiconductor export powerhouse.',
    overview: 'Idaho\'s trade profile combines agriculture and high tech. Micron Technology, headquartered in Boise, is one of the world\'s largest memory chip manufacturers. The state also exports significant quantities of dairy products, potatoes, and lumber. Lewiston is the farthest-inland seaport in the Pacific Northwest.',
  },
  {
    slug: 'illinois', name: 'Illinois', code: 'IL',
    majorPorts: ['Port of Chicago', 'Chicago O\'Hare (air cargo)', 'Inland waterway ports'],
    topTradePartners: ['Canada', 'China', 'Mexico', 'Germany', 'Japan'],
    topImports: ['Machinery', 'Electronics', 'Vehicles', 'Pharmaceuticals', 'Iron & steel'],
    topExports: ['Machinery', 'Soybeans', 'Vehicles', 'Chemicals', 'Medical instruments'],
    importVolume: '$105B annually', exportVolume: '$65B annually',
    tradeHighlight: 'Chicago O\'Hare is the busiest US air cargo hub, and Chicago is the nation\'s #1 rail hub.',
    overview: 'Illinois sits at the center of America\'s freight network. Chicago\'s rail yards, O\'Hare air cargo facilities, and Great Lakes port make it a distribution nexus for the entire Midwest. The state imports heavily for its manufacturing base (Caterpillar, John Deere, Abbott Labs) and exports agricultural products and industrial machinery.',
  },
  {
    slug: 'indiana', name: 'Indiana', code: 'IN',
    majorPorts: ['Port of Indiana-Burns Harbor', 'Port of Indiana-Jeffersonville', 'Port of Indiana-Mount Vernon'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Japan', 'Germany'],
    topImports: ['Vehicles & parts', 'Machinery', 'Pharmaceuticals', 'Iron & steel', 'Plastics'],
    topExports: ['Pharmaceuticals (Eli Lilly)', 'Vehicles', 'Machinery', 'Medical devices', 'Organic chemicals'],
    importVolume: '$45B annually', exportVolume: '$40B annually',
    tradeHighlight: 'Indiana is the #1 US steel-producing state and a major pharmaceutical exporter via Eli Lilly.',
    overview: 'Indiana\'s three Ohio River and Great Lakes ports connect it to global trade. The state is a major manufacturing hub with Toyota, Subaru, and Honda assembly plants. Eli Lilly in Indianapolis drives pharmaceutical exports, and Indiana produces more steel than any other state.',
  },
  {
    slug: 'iowa', name: 'Iowa', code: 'IA',
    majorPorts: ['Inland river ports on Mississippi'],
    topTradePartners: ['Canada', 'Mexico', 'Japan', 'China', 'Australia'],
    topImports: ['Machinery', 'Vehicles', 'Fertilizers', 'Iron & steel', 'Plastics'],
    topExports: ['Soybeans', 'Corn', 'Pork', 'Machinery (John Deere)', 'Ethanol'],
    importVolume: '$10B annually', exportVolume: '$14B annually',
    tradeHighlight: 'Iowa is a net exporter — agricultural products and machinery outpace imports.',
    overview: 'Iowa\'s trade is dominated by agriculture. The state is one of the top soybean and corn producers, with exports flowing down the Mississippi River to Gulf ports for shipment to Asia. John Deere, headquartered in Moline (IL) but with major Iowa operations, drives heavy machinery exports.',
  },
  {
    slug: 'kansas', name: 'Kansas', code: 'KS',
    majorPorts: ['Kansas City inland port / Foreign Trade Zone'],
    topTradePartners: ['Canada', 'Mexico', 'Japan', 'China', 'United Kingdom'],
    topImports: ['Vehicles', 'Machinery', 'Iron & steel', 'Electronics', 'Plastics'],
    topExports: ['Civilian aircraft (Textron/Cessna, Spirit AeroSystems)', 'Wheat', 'Beef', 'Machinery', 'Soybeans'],
    importVolume: '$8B annually', exportVolume: '$12B annually',
    tradeHighlight: 'Wichita is the "Air Capital of the World" — Cessna, Beechcraft, Learjet, and Spirit AeroSystems drive aircraft exports.',
    overview: 'Kansas is a major aerospace manufacturing state. Wichita\'s aviation cluster produces more general aviation aircraft than anywhere else in the world. Spirit AeroSystems makes fuselages for Boeing. Agriculture also features prominently — Kansas is typically the #1 wheat-producing state.',
  },
  {
    slug: 'kentucky', name: 'Kentucky', code: 'KY',
    majorPorts: ['Port of Louisville (UPS Worldport)', 'Paducah river port'],
    topTradePartners: ['Canada', 'United Kingdom', 'Japan', 'France', 'Germany'],
    topImports: ['Vehicles & parts', 'Machinery', 'Pharmaceuticals', 'Electronics', 'Apparel'],
    topExports: ['Aerospace products', 'Vehicles (Toyota)', 'Bourbon whiskey', 'Pharmaceuticals', 'Machinery'],
    importVolume: '$30B annually', exportVolume: '$32B annually',
    tradeHighlight: 'UPS Worldport in Louisville is the world\'s largest automated package-sorting facility — 2M+ packages per day.',
    overview: 'Kentucky\'s trade is powered by UPS Worldport at Louisville International Airport, the largest automated package hub globally. Toyota\'s Georgetown plant is one of the company\'s largest outside Japan. Kentucky bourbon is a signature export, with $1.5B+ in annual spirits exports.',
  },
  {
    slug: 'louisiana', name: 'Louisiana', code: 'LA',
    majorPorts: ['Port of South Louisiana', 'Port of New Orleans', 'Port of Baton Rouge', 'Port of Lake Charles'],
    topTradePartners: ['China', 'Mexico', 'Japan', 'South Korea', 'Netherlands'],
    topImports: ['Petroleum', 'Chemicals', 'Iron & steel', 'Machinery', 'Aluminum'],
    topExports: ['Petroleum products', 'Soybeans', 'Corn', 'Chemicals', 'LNG'],
    importVolume: '$55B annually', exportVolume: '$65B annually',
    tradeHighlight: 'The Port of South Louisiana is the largest port in the Western Hemisphere by tonnage.',
    overview: 'Louisiana\'s Mississippi River ports form the largest port complex in the Western Hemisphere. The Port of South Louisiana alone handles 300M+ tons annually. The state is a critical node for petroleum imports/exports, grain shipments, and increasingly LNG exports from Sabine Pass and Cameron.',
  },
  {
    slug: 'maine', name: 'Maine', code: 'ME',
    majorPorts: ['Port of Portland', 'Port of Eastport', 'Port of Searsport'],
    topTradePartners: ['Canada', 'China', 'Germany', 'Ireland', 'United Kingdom'],
    topImports: ['Petroleum products', 'Seafood', 'Paper products', 'Machinery', 'Vehicles'],
    topExports: ['Lobster', 'Semiconductors (formerly)', 'Paper products', 'Blueberries', 'Lumber'],
    importVolume: '$5B annually', exportVolume: '$3B annually',
    tradeHighlight: 'Maine lobster is a globally recognized export — China was the top buyer before tariff disruptions.',
    overview: 'Maine\'s trade centers on natural resources. Lobster exports were worth $600M+ annually before US-China tariff disruptions redirected much of the catch to domestic markets. The state\'s paper and lumber industries drive trade with Canada, and petroleum imports through Portland supply northern New England.',
  },
  {
    slug: 'maryland', name: 'Maryland', code: 'MD',
    majorPorts: ['Port of Baltimore'],
    topTradePartners: ['Germany', 'China', 'Brazil', 'Japan', 'United Kingdom'],
    topImports: ['Vehicles', 'Machinery', 'Iron & steel', 'Sugar', 'Aluminum'],
    topExports: ['Vehicles', 'Aerospace products', 'Coal', 'Chemicals', 'Medical instruments'],
    importVolume: '$35B annually', exportVolume: '$12B annually',
    tradeHighlight: 'The Port of Baltimore is the #1 US port for auto imports — handling 850,000+ vehicles per year.',
    overview: 'The Port of Baltimore specializes in roll-on/roll-off cargo, making it the nation\'s top port for imported automobiles and light trucks. The port\'s 50-foot channel accommodates the largest vessels on the East Coast. After the 2024 Key Bridge collapse, the port rapidly rebuilt operations.',
  },
  {
    slug: 'massachusetts', name: 'Massachusetts', code: 'MA',
    majorPorts: ['Port of Boston (Conley Terminal)', 'New Bedford'],
    topTradePartners: ['China', 'Ireland', 'Germany', 'Japan', 'United Kingdom'],
    topImports: ['Pharmaceuticals', 'Electronics', 'Machinery', 'LNG', 'Vehicles'],
    topExports: ['Pharmaceuticals', 'Medical instruments', 'Semiconductors', 'Fish & seafood', 'Industrial machinery'],
    importVolume: '$30B annually', exportVolume: '$30B annually',
    tradeHighlight: 'Massachusetts leads the US in biotech and pharma exports, with companies like Moderna, Biogen, and Vertex.',
    overview: 'Massachusetts is a biotech and pharmaceutical trade hub. The Cambridge/Boston biotech cluster exports billions in pharma products. The Port of Boston handles containerized cargo and LNG imports, while New Bedford is the #1 US fishing port by value.',
  },
  {
    slug: 'michigan', name: 'Michigan', code: 'MI',
    majorPorts: ['Port of Detroit', 'Ambassador Bridge', 'Blue Water Bridge', 'Port of Muskegon'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Japan', 'Germany'],
    topImports: ['Vehicles & auto parts', 'Machinery', 'Iron & steel', 'Plastics', 'Engines'],
    topExports: ['Vehicles & auto parts', 'Machinery', 'Pharmaceuticals', 'Chemicals', 'Iron & steel'],
    importVolume: '$120B annually', exportVolume: '$60B annually',
    tradeHighlight: 'The Ambassador Bridge carries 25% of all US-Canada trade — the busiest international land crossing in North America.',
    overview: 'Michigan\'s trade is defined by the auto industry. Detroit\'s Big Three (GM, Ford, Stellantis) drive massive cross-border parts and vehicle flows with Canada and Mexico. The Ambassador Bridge and the new Gordie Howe International Bridge are critical infrastructure for the integrated North American auto supply chain.',
  },
  {
    slug: 'minnesota', name: 'Minnesota', code: 'MN',
    majorPorts: ['Port of Duluth-Superior', 'Minneapolis-St. Paul air cargo'],
    topTradePartners: ['Canada', 'China', 'Mexico', 'Ireland', 'Germany'],
    topImports: ['Machinery', 'Electronics', 'Vehicles', 'Pharmaceuticals', 'Medical devices'],
    topExports: ['Medical devices (Medtronic, 3M)', 'Soybeans', 'Machinery', 'Optical instruments', 'Corn'],
    importVolume: '$28B annually', exportVolume: '$24B annually',
    tradeHighlight: 'Minnesota is the #1 US state for medical device exports — Medtronic, 3M, and Abbott drive the sector.',
    overview: 'Minnesota combines agricultural exports with high-tech manufacturing. The state is the nation\'s top medical device exporter, with Medtronic and 3M headquartered in the Twin Cities. The Port of Duluth-Superior on Lake Superior handles iron ore and grain shipments.',
  },
  {
    slug: 'mississippi', name: 'Mississippi', code: 'MS',
    majorPorts: ['Port of Gulfport', 'Port of Pascagoula', 'Port of Vicksburg'],
    topTradePartners: ['China', 'Mexico', 'Japan', 'Canada', 'Brazil'],
    topImports: ['Petroleum', 'Machinery', 'Vehicles', 'Iron & steel', 'Chemicals'],
    topExports: ['Petroleum products', 'Poultry', 'Ships & boats', 'Soybeans', 'Cotton'],
    importVolume: '$14B annually', exportVolume: '$12B annually',
    tradeHighlight: 'Ingalls Shipbuilding in Pascagoula builds US Navy destroyers — a major defense export contributor.',
    overview: 'Mississippi\'s Gulf Coast ports handle petroleum, chemicals, and agricultural products. Ingalls Shipbuilding at Pascagoula is one of the nation\'s largest military shipyards. The state exports significant quantities of poultry and soybeans through Gulf ports.',
  },
  {
    slug: 'missouri', name: 'Missouri', code: 'MO',
    majorPorts: ['Port of St. Louis', 'Kansas City inland port'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Germany', 'Japan'],
    topImports: ['Vehicles', 'Machinery', 'Electronics', 'Pharmaceuticals', 'Iron & steel'],
    topExports: ['Soybeans', 'Vehicles', 'Chemicals', 'Machinery', 'Meat products'],
    importVolume: '$18B annually', exportVolume: '$15B annually',
    tradeHighlight: 'St. Louis sits at the confluence of the Missouri and Mississippi Rivers — a natural trade crossroads.',
    overview: 'Missouri benefits from its central location and river access. St. Louis and Kansas City serve as major distribution hubs for the Midwest. The state\'s diverse manufacturing base includes GM and Ford assembly plants, Bayer crop science, and Anheuser-Busch.',
  },
  {
    slug: 'montana', name: 'Montana', code: 'MT',
    majorPorts: ['Sweetgrass-Coutts border crossing'],
    topTradePartners: ['Canada', 'Japan', 'South Korea', 'China', 'Mexico'],
    topImports: ['Petroleum', 'Vehicles', 'Machinery', 'Fertilizers', 'Iron & steel'],
    topExports: ['Wheat', 'Petroleum products', 'Coal', 'Precious metals', 'Cattle'],
    importVolume: '$3B annually', exportVolume: '$2B annually',
    tradeHighlight: 'Montana\'s trade flows primarily north to Canada — the Sweetgrass border crossing is a major truck route.',
    overview: 'Montana\'s trade is dominated by agriculture and natural resources. The state exports wheat to Asia and petroleum to Canada. The Canadian border is the primary trade corridor, with Montana handling significant cross-border energy and agricultural flows.',
  },
  {
    slug: 'nebraska', name: 'Nebraska', code: 'NE',
    majorPorts: ['Inland (no seaport)'],
    topTradePartners: ['Canada', 'Mexico', 'Japan', 'China', 'South Korea'],
    topImports: ['Machinery', 'Vehicles', 'Electronics', 'Fertilizers', 'Iron & steel'],
    topExports: ['Beef', 'Soybeans', 'Corn', 'Machinery', 'Processed food'],
    importVolume: '$6B annually', exportVolume: '$8B annually',
    tradeHighlight: 'Nebraska is one of the top US beef exporters — Japan and South Korea are major buyers.',
    overview: 'Nebraska\'s exports exceed imports, driven by agriculture and food processing. The state is a top beef and corn producer. Major food processing companies (Tyson, Cargill, ConAgra) have significant operations, and Warren Buffett\'s Berkshire Hathaway is headquartered in Omaha.',
  },
  {
    slug: 'nevada', name: 'Nevada', code: 'NV',
    majorPorts: ['Las Vegas air cargo', 'Reno distribution hubs'],
    topTradePartners: ['Canada', 'Switzerland', 'China', 'Mexico', 'Japan'],
    topImports: ['Gold', 'Machinery', 'Electronics', 'Vehicles', 'Precious stones'],
    topExports: ['Gold', 'Minerals', 'Machinery', 'Electronics', 'Food products'],
    importVolume: '$8B annually', exportVolume: '$10B annually',
    tradeHighlight: 'Nevada is the #1 US gold-producing state — precious metals dominate its trade profile.',
    overview: 'Nevada\'s trade is shaped by mining and logistics. The state produces 75% of US gold output. Reno has become a major e-commerce distribution hub (Tesla Gigafactory, Amazon, Switch data centers) with easy access to California ports. Las Vegas handles air cargo for the tourism and convention industry.',
  },
  {
    slug: 'new-hampshire', name: 'New Hampshire', code: 'NH',
    majorPorts: ['Port of Portsmouth (minor)'],
    topTradePartners: ['Canada', 'Mexico', 'Malaysia', 'China', 'Germany'],
    topImports: ['Electronics', 'Machinery', 'Vehicles', 'Optical instruments', 'Plastics'],
    topExports: ['Semiconductors', 'Machinery', 'Computers', 'Electrical equipment', 'Medical instruments'],
    importVolume: '$6B annually', exportVolume: '$5B annually',
    tradeHighlight: 'New Hampshire has a significant tech manufacturing sector — BAE Systems and DEKA Research drive exports.',
    overview: 'New Hampshire\'s trade punches above its weight due to a strong tech and defense manufacturing sector. BAE Systems has major facilities, and the state exports semiconductors and precision instruments. Most international cargo routes through Boston\'s port.',
  },
  {
    slug: 'new-jersey', name: 'New Jersey', code: 'NJ',
    majorPorts: ['Port Newark-Elizabeth Marine Terminal (Port of NY/NJ)'],
    topTradePartners: ['China', 'Germany', 'India', 'United Kingdom', 'Italy'],
    topImports: ['Pharmaceuticals', 'Electronics', 'Machinery', 'Vehicles', 'Apparel'],
    topExports: ['Pharmaceuticals', 'Chemicals', 'Machinery', 'Plastics', 'Medical instruments'],
    importVolume: '$140B annually', exportVolume: '$40B annually',
    tradeHighlight: 'Port Newark is the busiest port on the East Coast — handling $200B+ in cargo annually.',
    overview: 'New Jersey hosts the East Coast\'s largest port facility. Port Newark-Elizabeth Marine Terminal handles more container traffic than any other East Coast port. The state is also the pharmaceutical capital of the US, with J&J, Merck, and dozens of other pharma companies driving trade in medical products.',
  },
  {
    slug: 'new-mexico', name: 'New Mexico', code: 'NM',
    majorPorts: ['Santa Teresa Port of Entry', 'Columbus Port of Entry'],
    topTradePartners: ['Mexico', 'China', 'Canada', 'Japan', 'Germany'],
    topImports: ['Electronics', 'Vehicles', 'Machinery', 'Petroleum', 'Electrical equipment'],
    topExports: ['Electronics', 'Petroleum', 'Semiconductors', 'Dairy products', 'Pecans'],
    importVolume: '$6B annually', exportVolume: '$4B annually',
    tradeHighlight: 'The Santa Teresa port complex is one of the fastest-growing US-Mexico border crossings.',
    overview: 'New Mexico\'s trade is heavily oriented toward Mexico. The Santa Teresa industrial complex near Las Cruces has grown rapidly as an alternative to congested El Paso crossings. Intel operates a major semiconductor fab in Rio Rancho, and the state\'s oil production in the Permian Basin drives petroleum exports.',
  },
  {
    slug: 'new-york', name: 'New York', code: 'NY',
    majorPorts: ['Port of New York/New Jersey', 'JFK International Airport (air cargo)', 'Port of Albany'],
    topTradePartners: ['China', 'Switzerland', 'Canada', 'United Kingdom', 'Japan'],
    topImports: ['Gold & precious metals', 'Diamonds', 'Pharmaceuticals', 'Art & antiques', 'Electronics'],
    topExports: ['Diamonds', 'Gold', 'Art & antiques', 'Pharmaceuticals', 'Financial services equipment'],
    importVolume: '$130B annually', exportVolume: '$80B annually',
    tradeHighlight: 'JFK Airport handles more international air cargo value than any US airport — driven by diamonds, gold, and pharmaceuticals.',
    overview: 'New York\'s trade reflects its role as a global financial and luxury center. JFK Airport handles enormous values of precious metals, diamonds, and art. The Port of NY/NJ (shared with New Jersey) is the East Coast\'s busiest container port. Wall Street\'s financial activities also drive trade in specialized equipment and services.',
  },
  {
    slug: 'north-carolina', name: 'North Carolina', code: 'NC',
    majorPorts: ['Port of Wilmington', 'Port of Morehead City'],
    topTradePartners: ['China', 'Canada', 'Mexico', 'Germany', 'Japan'],
    topImports: ['Machinery', 'Electronics', 'Pharmaceuticals', 'Vehicles', 'Furniture'],
    topExports: ['Pharmaceuticals', 'Tobacco', 'Machinery', 'Vehicles', 'Textiles'],
    importVolume: '$40B annually', exportVolume: '$35B annually',
    tradeHighlight: 'North Carolina\'s Research Triangle drives pharmaceutical and biotech exports.',
    overview: 'North Carolina has transformed from a textile and tobacco state to a pharmaceutical and tech hub. The Research Triangle (Raleigh-Durham-Chapel Hill) hosts major pharma companies. The Port of Wilmington handles containerized cargo, and Charlotte is a major banking center influencing trade finance.',
  },
  {
    slug: 'north-dakota', name: 'North Dakota', code: 'ND',
    majorPorts: ['Portal border crossing', 'Pembina border crossing'],
    topTradePartners: ['Canada', 'Mexico', 'Japan', 'Norway', 'South Korea'],
    topImports: ['Machinery', 'Vehicles', 'Petroleum', 'Fertilizers', 'Iron & steel'],
    topExports: ['Soybeans', 'Wheat', 'Petroleum (crude oil)', 'Machinery', 'Dried beans'],
    importVolume: '$3B annually', exportVolume: '$5B annually',
    tradeHighlight: 'Bakken Formation oil production has made North Dakota a major petroleum exporter since 2010.',
    overview: 'North Dakota\'s trade has been transformed by the Bakken oil boom. Crude oil is now the state\'s top export, shipped by rail and pipeline. Traditional agricultural exports (wheat, soybeans) remain strong. Cross-border trade with Canada\'s Saskatchewan and Manitoba provinces is significant.',
  },
  {
    slug: 'ohio', name: 'Ohio', code: 'OH',
    majorPorts: ['Port of Cleveland', 'Port of Toledo', 'Port of Cincinnati'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Japan', 'Germany'],
    topImports: ['Vehicles & parts', 'Machinery', 'Iron & steel', 'Electronics', 'Plastics'],
    topExports: ['Vehicles', 'Aerospace products', 'Machinery', 'Chemicals', 'Plastics'],
    importVolume: '$60B annually', exportVolume: '$55B annually',
    tradeHighlight: 'Ohio is a top-5 US manufacturing state with Honda, GM, and GE Aviation driving trade.',
    overview: 'Ohio\'s manufacturing base drives substantial two-way trade. Honda has major assembly plants in Marysville, and GE Aviation in Cincinnati produces jet engines. Great Lakes ports handle iron ore and steel, and Ohio\'s central location makes it a logistics hub for the eastern US.',
  },
  {
    slug: 'oklahoma', name: 'Oklahoma', code: 'OK',
    majorPorts: ['Port of Catoosa (McClellan-Kerr Waterway)', 'Port of Muskogee'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Japan', 'United Kingdom'],
    topImports: ['Machinery', 'Vehicles', 'Iron & steel', 'Electronics', 'Petroleum equipment'],
    topExports: ['Machinery', 'Petroleum products', 'Aircraft parts', 'Vehicles', 'Meat'],
    importVolume: '$8B annually', exportVolume: '$7B annually',
    tradeHighlight: 'Oklahoma\'s inland waterway system connects Tulsa to the Gulf of Mexico via the Arkansas River.',
    overview: 'Oklahoma\'s trade centers on oil and gas, aerospace, and agriculture. The McClellan-Kerr Arkansas River Navigation System gives Tulsa barge access to Gulf ports. The state has a significant aerospace sector with American Airlines maintenance, Boeing defense, and Tinker Air Force Base.',
  },
  {
    slug: 'oregon', name: 'Oregon', code: 'OR',
    majorPorts: ['Port of Portland', 'Port of Coos Bay'],
    topTradePartners: ['China', 'Japan', 'South Korea', 'Canada', 'Malaysia'],
    topImports: ['Vehicles', 'Machinery', 'Electronics', 'Iron & steel', 'Aluminum'],
    topExports: ['Semiconductors (Intel)', 'Wheat', 'Hay', 'Potash', 'Lumber'],
    importVolume: '$22B annually', exportVolume: '$22B annually',
    tradeHighlight: 'Intel\'s massive Hillsboro fab complex makes Oregon a top semiconductor exporter.',
    overview: 'Oregon\'s trade reflects its dual economy of tech and natural resources. Intel\'s Oregon campus is one of the company\'s largest manufacturing sites. The Port of Portland handles auto imports and grain exports. Oregon wheat and hay are major agricultural exports to Asian markets.',
  },
  {
    slug: 'pennsylvania', name: 'Pennsylvania', code: 'PA',
    majorPorts: ['PhilaPort (Port of Philadelphia)', 'Port of Pittsburgh (inland)'],
    topTradePartners: ['Canada', 'China', 'Germany', 'United Kingdom', 'Mexico'],
    topImports: ['Petroleum', 'Machinery', 'Pharmaceuticals', 'Vehicles', 'Iron & steel'],
    topExports: ['Chemicals', 'Pharmaceuticals', 'Machinery', 'Coal', 'Plastics'],
    importVolume: '$50B annually', exportVolume: '$42B annually',
    tradeHighlight: 'PhilaPort handles the most international perishable cargo on the East Coast.',
    overview: 'Pennsylvania is a diversified trade state with PhilaPort handling containers, perishable goods, and cocoa beans. The state\'s pharmaceutical industry (GSK, Merck operations), steel legacy, and energy sector (Marcellus Shale natural gas) drive diverse trade flows. Pittsburgh\'s inland port moves coal and industrial cargo.',
  },
  {
    slug: 'rhode-island', name: 'Rhode Island', code: 'RI',
    majorPorts: ['Port of Providence', 'Quonset Point/Davisville'],
    topTradePartners: ['Canada', 'Germany', 'China', 'Italy', 'United Kingdom'],
    topImports: ['Vehicles', 'Petroleum', 'Machinery', 'Iron & steel', 'Chemicals'],
    topExports: ['Machinery', 'Precious metals', 'Electrical equipment', 'Plastics', 'Fish & seafood'],
    importVolume: '$4B annually', exportVolume: '$2B annually',
    tradeHighlight: 'Quonset Point is a major auto import terminal on the East Coast.',
    overview: 'Rhode Island\'s trade is concentrated at Providence and Quonset Point. The Davisville auto terminal handles vehicle imports. Despite its small size, the state has a strong jewelry manufacturing tradition and exports precision machinery and electrical equipment.',
  },
  {
    slug: 'south-carolina', name: 'South Carolina', code: 'SC',
    majorPorts: ['Port of Charleston'],
    topTradePartners: ['Germany', 'China', 'Canada', 'Japan', 'United Kingdom'],
    topImports: ['Vehicles (BMW)', 'Machinery', 'Tires', 'Iron & steel', 'Plastics'],
    topExports: ['Vehicles (BMW)', 'Tires (Michelin)', 'Machinery', 'Plastics', 'Aircraft parts'],
    importVolume: '$40B annually', exportVolume: '$35B annually',
    tradeHighlight: 'BMW\'s Spartanburg plant is the company\'s largest factory globally — 60% of vehicles are exported.',
    overview: 'South Carolina has become a major automotive and tire manufacturing state. BMW\'s Spartanburg plant produces 1,500 vehicles daily, mostly for export. Michelin\'s North American HQ is in Greenville. The Port of Charleston is one of the fastest-growing container ports on the East Coast.',
  },
  {
    slug: 'south-dakota', name: 'South Dakota', code: 'SD',
    majorPorts: ['Inland (no seaport)'],
    topTradePartners: ['Canada', 'Mexico', 'Japan', 'China', 'South Korea'],
    topImports: ['Machinery', 'Vehicles', 'Electronics', 'Fertilizers', 'Iron & steel'],
    topExports: ['Soybeans', 'Corn', 'Beef', 'Processed food', 'Machinery'],
    importVolume: '$2B annually', exportVolume: '$3.5B annually',
    tradeHighlight: 'South Dakota is a net exporter driven by agricultural commodities.',
    overview: 'South Dakota\'s trade is agricultural. Soybeans and corn are the primary exports, shipped to Asian markets via Gulf and Pacific Northwest ports. The state has no seaport, but its agricultural output connects to global supply chains through rail and barge networks.',
  },
  {
    slug: 'tennessee', name: 'Tennessee', code: 'TN',
    majorPorts: ['Port of Memphis', 'Nashville air cargo'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Japan', 'Germany'],
    topImports: ['Vehicles & parts', 'Machinery', 'Electronics', 'Pharmaceuticals', 'Chemicals'],
    topExports: ['Vehicles (Nissan, VW)', 'Medical instruments', 'Chemicals', 'Cotton', 'Machinery'],
    importVolume: '$45B annually', exportVolume: '$35B annually',
    tradeHighlight: 'Memphis is the world\'s busiest cargo airport — FedEx\'s global SuperHub processes 4M+ packages daily.',
    overview: 'Tennessee\'s trade infrastructure is exceptional. FedEx\'s Memphis SuperHub makes it the world\'s busiest air cargo airport. Nissan and Volkswagen have major assembly plants. The state\'s central location, FedEx hub, and river access make it a top distribution location for imports and exports.',
  },
  {
    slug: 'texas', name: 'Texas', code: 'TX',
    majorPorts: ['Port of Houston', 'Port of Laredo', 'Port of Beaumont', 'Port of Corpus Christi', 'DFW Airport cargo'],
    topTradePartners: ['Mexico', 'China', 'Canada', 'South Korea', 'Brazil'],
    topImports: ['Petroleum', 'Electronics', 'Vehicles', 'Machinery', 'Chemicals'],
    topExports: ['Petroleum products', 'Chemicals', 'Electronics', 'Machinery', 'Vehicles'],
    importVolume: '$350B annually', exportVolume: '$375B annually',
    tradeHighlight: 'Texas exports more than any other state, and the Port of Houston is the #1 US port by foreign tonnage.',
    overview: 'Texas is the #1 US trading state by exports. The Port of Houston handles more foreign tonnage than any US port, driven by the petrochemical industry. Laredo is the busiest land port on the US-Mexico border. Texas also has a massive semiconductor sector (Texas Instruments, Samsung fab in Taylor) and the nation\'s largest refining complex.',
  },
  {
    slug: 'utah', name: 'Utah', code: 'UT',
    majorPorts: ['Salt Lake City air cargo', 'Inland Port Authority'],
    topTradePartners: ['United Kingdom', 'Canada', 'China', 'Mexico', 'Japan'],
    topImports: ['Gold', 'Machinery', 'Electronics', 'Vehicles', 'Precious metals'],
    topExports: ['Gold', 'Copper', 'Medical instruments', 'Machinery', 'Semiconductors'],
    importVolume: '$14B annually', exportVolume: '$13B annually',
    tradeHighlight: 'Utah\'s new Inland Port in Salt Lake City aims to become a major intermodal freight hub.',
    overview: 'Utah\'s trade combines mining and tech. The state is a major producer of gold, copper, and other minerals. The new Utah Inland Port Authority near Salt Lake City is designed to improve freight connections and reduce costs for Utah businesses accessing West Coast ports.',
  },
  {
    slug: 'vermont', name: 'Vermont', code: 'VT',
    majorPorts: ['Highgate Springs border crossing', 'Derby Line border crossing'],
    topTradePartners: ['Canada', 'Taiwan', 'China', 'Germany', 'Ireland'],
    topImports: ['Electronics', 'Machinery', 'Vehicles', 'Dairy products', 'Lumber'],
    topExports: ['Semiconductors (GlobalFoundries)', 'Machinery', 'Dairy', 'Maple syrup', 'Electrical equipment'],
    importVolume: '$4B annually', exportVolume: '$3B annually',
    tradeHighlight: 'GlobalFoundries\' Essex Junction fab makes Vermont a disproportionate semiconductor exporter.',
    overview: 'Vermont\'s trade is surprisingly tech-heavy due to GlobalFoundries\' semiconductor fabrication plant in Essex Junction. The state also exports dairy products, specialty foods (maple syrup), and precision machinery. Cross-border trade with Quebec is significant.',
  },
  {
    slug: 'virginia', name: 'Virginia', code: 'VA',
    majorPorts: ['Port of Virginia (Norfolk)', 'Port of Richmond'],
    topTradePartners: ['China', 'Germany', 'Canada', 'Brazil', 'United Kingdom'],
    topImports: ['Vehicles', 'Machinery', 'Electronics', 'Furniture', 'Apparel'],
    topExports: ['Soybeans', 'Tobacco', 'Coal', 'Vehicles', 'Chemicals'],
    importVolume: '$45B annually', exportVolume: '$20B annually',
    tradeHighlight: 'The Port of Virginia (Norfolk) has 55-foot channels — deep enough for the largest container ships.',
    overview: 'The Port of Virginia at Norfolk is the deepest port on the East Coast, capable of handling fully loaded ultra-large container vessels. The port has invested heavily in automation and expansion. Virginia also benefits from its proximity to Washington DC, with significant government and defense-related trade.',
  },
  {
    slug: 'washington', name: 'Washington', code: 'WA',
    majorPorts: ['Port of Seattle', 'Port of Tacoma (Northwest Seaport Alliance)', 'Port of Vancouver USA'],
    topTradePartners: ['China', 'Japan', 'Canada', 'South Korea', 'Taiwan'],
    topImports: ['Electronics', 'Vehicles', 'Machinery', 'Apparel', 'Furniture'],
    topExports: ['Aircraft (Boeing)', 'Soybeans', 'Corn', 'Apples', 'Seafood'],
    importVolume: '$90B annually', exportVolume: '$55B annually',
    tradeHighlight: 'Boeing\'s Everett and Renton factories make Washington the #1 US state for aircraft exports.',
    overview: 'Washington state is a Pacific trade gateway. The Northwest Seaport Alliance (Seattle + Tacoma) is the 4th-largest US container port complex. Boeing\'s commercial aircraft production in Everett makes aerospace the top export. The state also exports major quantities of agricultural products (apples, wheat, seafood) to Asia.',
  },
  {
    slug: 'west-virginia', name: 'West Virginia', code: 'WV',
    majorPorts: ['Inland river ports on Ohio/Kanawha Rivers'],
    topTradePartners: ['Canada', 'China', 'India', 'Brazil', 'Japan'],
    topImports: ['Machinery', 'Vehicles', 'Iron & steel', 'Chemicals', 'Aluminum'],
    topExports: ['Coal', 'Chemicals', 'Machinery', 'Vehicles', 'Wood products'],
    importVolume: '$5B annually', exportVolume: '$6B annually',
    tradeHighlight: 'West Virginia is one of the top US coal-exporting states, shipping primarily to India and Asia.',
    overview: 'West Virginia\'s trade is dominated by coal and chemicals. The state\'s Appalachian coal mines produce metallurgical and thermal coal for export. Chemical manufacturing along the Kanawha Valley drives additional trade. Inland river ports connect to the Mississippi River system and Gulf Coast ports.',
  },
  {
    slug: 'wisconsin', name: 'Wisconsin', code: 'WI',
    majorPorts: ['Port of Milwaukee', 'Port of Green Bay', 'Port of Superior'],
    topTradePartners: ['Canada', 'Mexico', 'China', 'Germany', 'Japan'],
    topImports: ['Machinery', 'Vehicles', 'Iron & steel', 'Electronics', 'Plastics'],
    topExports: ['Machinery', 'Medical instruments', 'Vehicles', 'Dairy products', 'Paper'],
    importVolume: '$25B annually', exportVolume: '$24B annually',
    tradeHighlight: 'Wisconsin exports more industrial machinery per capita than almost any US state.',
    overview: 'Wisconsin\'s manufacturing tradition drives its trade. The state produces industrial machinery, medical devices, and paper products. Great Lakes ports handle iron ore and grain. Wisconsin cheese and dairy products are exported globally, and Oshkosh Defense is a major military vehicle manufacturer.',
  },
  {
    slug: 'wyoming', name: 'Wyoming', code: 'WY',
    majorPorts: ['Inland (no seaport)'],
    topTradePartners: ['Canada', 'Japan', 'South Korea', 'India', 'China'],
    topImports: ['Machinery', 'Vehicles', 'Electronics', 'Iron & steel', 'Chemicals'],
    topExports: ['Coal', 'Soda ash', 'Petroleum products', 'Bentonite', 'Cattle'],
    importVolume: '$1B annually', exportVolume: '$2B annually',
    tradeHighlight: 'Wyoming produces 40% of US coal and 90% of US soda ash (used in glass manufacturing worldwide).',
    overview: 'Wyoming\'s trade is resource-based. The state\'s Powder River Basin produces the most coal of any US region. Wyoming is also the world\'s largest producer of soda ash (natural trona), exported globally for glass manufacturing. Low population but high per-capita export value.',
  },
  {
    slug: 'district-of-columbia', name: 'District of Columbia', code: 'DC',
    majorPorts: ['No commercial port (uses Virginia/Maryland ports)'],
    topTradePartners: ['Canada', 'United Kingdom', 'China', 'Germany', 'Japan'],
    topImports: ['Art & antiques', 'Books & media', 'Electronics', 'Vehicles', 'Scientific instruments'],
    topExports: ['Services (consulting, legal, lobbying)', 'Art & antiques', 'Books & media', 'Electronics', 'Scientific instruments'],
    importVolume: '$2B annually', exportVolume: '$2B annually',
    tradeHighlight: 'DC\'s trade influence vastly exceeds its merchandise numbers — trade policy is made here.',
    overview: 'The District of Columbia\'s direct merchandise trade is minimal, but its policy influence is enormous. USTR, Commerce Department, CBP headquarters, and the ITC are all located in DC. Embassies and trade associations drive services trade. Physical goods move through Virginia and Maryland ports.',
  },
];

export function getAllStates(): StateTradeData[] {
  return states;
}

export function getStateBySlug(slug: string): StateTradeData | undefined {
  return states.find((s) => s.slug === slug);
}
